### ISSUE TITLE
Some peers don't appear for certain routers / wifi connections

### ISSUE THREAD

**Issue by dwblair** [cabal-club/cabal-cli#102]
Howdy!

  I think this might be more of an issue with networking / 'swarm' connections -- but I thought I'd put the observation here, in case it's useful.  I've noticed that when I connect to cabal using e.g. the wifi in a coffee shop, sometimes I don't see peers whom I know to be online; and then, when I switch to using my phone's wifi hotspot, I do see those peers.  

It made me think: because of the stochastic nature of p2p networking, an interesting 'debug your connection' mode might be to have reliable 'superpeers' that we know are online, and to see whether one's local cabal can reach them.  If one can't then this might help to map out what connection 'topologies' are possible with the current setup (e.g. 'local wifi is working, but global internet isn't' or something).

Cheerio!
Don

**Comment by noffle** [comment]
This is actually how discovery works (as of `discovery-swarm`)! It connects to a set of well-known servers, and uses those to discover peer IP addresses. We just don't expose the status of those connections.

@dwblair are you ok if I edit your issue title to be something more like "display network connectivity status" or something similar? It sounds like your intention was to have the client help differentiate between "you have no internet connection" and "no peers found"?

**Comment by noffle** [comment]
This has been significantly improved with our move to hyperswarm!
