### ISSUE TITLE
Replace scrubbed emojis with :emoji name:

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-cli#109]
To mitigate #55 I decided to replace all emoji with a cabal unicode character (hehe)

@cinnamon-bun had the great idea of finding a node module to replace the emojis with their name in text, like `:star:`. Which is fantastic!

### Implementation
* [ ] Find modules that do map emojis to their text representations
* [ ] Replace unicode emojis with their text!

**Comment by cinnamon-bun** [comment]
I researched emoji libraries for this: https://github.com/cabal-club/commons/issues/2
