### ISSUE TITLE
Use emitter.setmaxlisteners() to increase limit

### ISSUE THREAD

**Issue by cinnamon-bun** [cabal-club/cabal-cli#110]
This warning gets printed to the screen occasionally, messing up the display.

`Use emitter.setmaxlisteners() to increase limit`

Node v10.8.0 on OSX 10.11.6.  This is not the latest version of Node.

Discussion about hiding warnings in node here, but with no good solution: https://github.com/nodejs/node/issues/10802

**Comment by noffle** [comment]
One workaround for now is to tack `2> /dev/null` on the end of your command when you run cabal, since the warnings are written to stderr.

**Comment by noffle** [comment]
If it's the same output as me, the full warning text is

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 update listeners added. Use emitter.setMaxListeners() to increase limit
```

So we could be looking for emissions of the `'update'` event.

**Comment by noffle** [comment]
I think the culprit is probably here, where we have a listener inside of a listener:

https://github.com/cabal-club/cabal-cli/blob/master/neat-screen.js#L237

**Comment by noffle** [comment]
I think I've fixed it. @cinnamon-bun can you try cabal 6.3.4?

**Comment by cinnamon-bun** [comment]
@noffle The error message doesn't appear every single time so it's hard to test, but I'm not seeing it now!  🌟

**Comment by cblgh** [comment]
🎈 🍄
