### ISSUE TITLE
Unable to move channel down from !status

### ISSUE THREAD

**Issue by joehand** [cabal-club/cabal-cli#119]
I am unable to ctrl-n when I am on the !status channel thingy.

**Comment by substack** [comment]
have also experienced this on the main cabal for a while

**Comment by cblgh** [comment]
ya i think someone pushed a message to `!status` from the desktop so i gotta filter it out, i'll try to patch this and some other small things and push it out

**Comment by cblgh** [comment]
should be fixed in 7.1.1
