### ISSUE TITLE
Can't connect to any of the cabals

### ISSUE THREAD

**Issue by lostfile** [cabal-club/cabal-cli#131]
It seems if all of them are currently offline ive tried every key that was given to me none of them worked  do i need to port forward something is there something im doing wrong

**Comment by cblgh** [comment]
which cabals have you tried? :)

the previous public cabal has been deprecated (it was becoming a bit of a singleton), we'll probably spin up a new take on public cabals soon

**Comment by cblgh** [comment]
@lostfile i just created a new cabal that i'll idle in for the rest of the week if you wanna come by and say hi :)

```
cabal://4014719a1a331942bf304ed3ec2001cbc5a4bd475375d308278d25bb6a205b53
```

**Comment by lostfile** [comment]
@cblgh thanks i shall test it out once i get back home from work

**Comment by cblgh** [comment]
we saw lostfile in the new public cabal :) 

(note for people from the future: the cabal above might be abandoned as we will be cycling cabals going forward, check https://cabal.chat)

**Comment by lostfile1** [comment]
:wink:
