### ISSUE TITLE
render bug

### ISSUE THREAD

**Issue by noffle** [cabal-club/cabal-cli#133]
Saw this render bug today, which I think came from the desktop client:

![screenshot of cabal-cli with a message running over the edge of the message area and into the nick sidebar](http://eight45.net/pub/cabal-render-bug.png)

and here is the raw message:

```json
{"content":{"channel":"default","text":"> noffle\n> 5:42 PMNovember 2, 2019\n> Tio: the way peering works right now is, your node will look for all other peers currently online in the cabal, and connect to them. so, you're ALREADY connecting > to all available peers as it is\n\ni understand, but how can i chat privately with you for example?"},"type":"chat/text","timestamp":1572789466264}
```

**Comment by cblgh** [comment]
yup saw that too

then it disappeared for some reason when doing https://github.com/cabal-club/cabal-cli/pull/134

**Comment by cblgh** [comment]
think i fixed it just now tho ^_^ pr inc

![image](https://user-images.githubusercontent.com/3862362/68091608-11d6bc80-fe82-11e9-855b-2e92b28d3ddd.png)
