### ISSUE TITLE
Instructions for first use

### ISSUE THREAD

**Issue by Raynos** [cabal-club/cabal-cli#163]
Me and a friend tried to use cabal for private group chat.

We started a cabal with `cabal --new` and I shared the key it generated and had him connect to it.

We were both in a cabal session with only one user in it.

**Comment by Raynos** [comment]
Are there instructions in how to set up a new cabal key to be used for a private group of friends ?

**Comment by cblgh** [comment]
that's how you would do it @Raynos! i think both of you might have been behind particularly difficult [NATs](https://en.wikipedia.org/wiki/Network_address_translation#Issues_and_limitations) tho.

we just switched to our networking to use hyperswarm which is supposed to alleviate those kind of NAT-related issues, but we're still finding out how things _actually_ behave

most pragmatic solution atm is, if one of your friends has a computer with a well-configured firewall then have them join the cabal e.g. with a headless session using `cabal <cabal-key> --seed`

cc @noffle if you have different take or suggestion

**Comment by Raynos** [comment]
Right, my laptop is just a home network with a home modem, no ports exposed or anything.

Maybe running a cabal seed on an EC2 or an actual server would aid with this.

**Comment by cblgh** [comment]
closing this for now as this is more related to #171
