### ISSUE TITLE
how do I know if it's working?

### ISSUE THREAD

**Issue by dominictarr** [cabal-club/cabal-cli#171]
so I managed to create a new cabal... but I have no idea if it's talking to the internet.
A friend tried connecting and that didn't work. I know enough about dat to know there should be a discovery server somewhere... but I have no idea if it's connecting.

how do I know if it's working, even just a little bit?

**Comment by quite** [comment]
Maybe you need more friends, what's the cabal url? :)

**Comment by okdistribute** [comment]
@dominictarr check out this branch of hyperswarm/connect-test https://github.com/hyperswarm/connect-test/pull/1

We've also seen strange behavior with hyperswarm, there are some new bugfixes in the dht that came down the pipe from @mafintosh since you opened this issue

It could be somewhere further up the stack in cabal, if you're able to connect with hyperswarm.

**Comment by cblgh** [comment]
@dominictarr somewhat of an unsolved problem atm, but we have a small utility you can use in cabal if you run in seeder mode:

`node cli.js <cabal key> --seed`

it will give you output in terms of people connecting, downloading info from you, and such. currently we don't have that inside the ui though

**Comment by cblgh** [comment]
from @mafintosh in response to dom's original question:
```
11:25:39 <@mafintosh> cblgh: re dominics q, swarm.flush is handy for this. that
                      flush cb is called after all pending dht ops are done and all connections have
                      been tried resulting from that. if you don’t have any peers then, it wont work
                      (until someone connects to you or it reannounces ~7min later)
```

**Comment by noffle** [comment]
@dominictarr Back when you tried, we still hadn't fixed our hyperswarm (discovery dht) issues around NAT holepunching. This seems to have been fixed now, though certain NATs still are impenetrable. Closing this, but feel free to reopen if you're still having connection challenges.
