### ISSUE TITLE
Fix rendering breaking with overly long non-message strings

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-cli#186]
If a person sets a topic (or does some other action, like `/me <thing>` i presume) the current line-breaking will somehow break the rendering

this can be reproduced in the current public cabal by going to the `rust` channel with a small enough window size and going between it and any other channel

**Comment by hackergrrl** [comment]
This is (hopefully) now fixed by https://github.com/cabal-club/cabal-cli/pull/227. Please re-open if you can find a repro case.
