### ISSUE TITLE
Can cabal support chatting in emacs?

### ISSUE THREAD

**Issue by Imymirror** [cabal-club/cabal-cli#203]
I use [telega.el](https://github.com/zevlg/telega.el) to chat as telegram client in Emacs.

If cabal can chat in Emacs like telega, It will be perfect.

**Comment by noffle** [comment]
One approach could be to write a wrapper program in nodejs around `cabal-client` that reads commands from stdin and writes info to stdout. Then emacs could just spawn that script as a subprocess and interact with it via stdin/stdout streams. A good place to start would be @timgoeller's [cabal-bot-core](https://github.com/timgoeller/cabal-bot-core).
