### ISSUE TITLE
Does Cabal work in countries with restricted or censored Internet access?

### ISSUE THREAD

**Issue by livrasand** [cabal-club/cabal-cli#226]
Hello,

I'm interested in using Cabal and would like to know if it functions properly in countries where internet access is heavily restricted or censored. Specifically, I'm referring to countries such as:

- Crimea
- Eritrea
- Russia
- Singapore
- China
- Iran
- North Korea
- Saudi Arabia
- Turkey

Can you provide any information or experiences regarding the use of Cabal in these regions? Are there any known issues or workarounds to ensure connectivity and functionality?

Thank you for your assistance.

Best regards,
Livrädo Sandoval.

**Comment by hackergrrl** [comment]
Hi Livrädo,

Writing to you to say, basically, that "I'm not sure". I don't know enough about those countries' mechanisms for nework restrictions. As far as I know, Cabal hasn't been explicitly tested against them.

The new, upcoming Cable protocol[1] will have good support for Tor, which means it should be a viable means of chatting for countries' whose restrictions are circumventable using Tor.

[1] https://github.com/cabal-club/cable

**Comment by livrasand** [comment]
Okay, I appreciate you taking the time to respond. I'll keep an eye out for Cable updates.
