### ISSUE TITLE
implement marker for unread channels

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-cli#37]
i don't have time riiight now (but i figured i could post an issue and potentially let someone new to the project create their first PR!) but those of us using cabal have been feeling the need for a way to be notified of when a channel has new unread messages

this would be suuuuuper sweet!

**Comment by soyuka** [comment]
I thought about that but I'm not sure that implementing native system notifications is good (feels too intrusive). I thought about the terminal bell (raises the priority in my windows manager for example), but then again some might find this annoying. 

What would be our best option there? Maybe that right now a simple number next to the channel name would suffice?

**Comment by cblgh** [comment]
yeah, i was thinking a simple hilight (similar to how nicks are displayed atm) would be more than enough

just an indication that "hey something happened here" (and optionally changing the colour/adding `*` to notify you that you were mentioned?)

**Comment by cblgh** [comment]
@teh-f00l nobody is working on it atm, please go ahead and tackle it!
