### ISSUE TITLE
Doesn't show all of the new messages that arrive on first start

### ISSUE THREAD

**Issue by cinnamon-bun** [cabal-club/cabal-cli#42]
If you start up the CLI interface and it immediately fetches a bunch of new messages, sometimes not all of the new messages will show.

If you quit and restart, the missing messages will be there.

The missing messages can be in the middle, not always at the end of the screen.

I don't know how to reproduce this.  It happened after I was offline for about a day.  Maybe upon booting and doing a first sync, some of the incoming messages slip through before event handlers get applied which would refresh the screen?

**Comment by cblgh** [comment]
this is way old and many major (and architectural) changes since opening, let's create a new issue if this sort of behaviour reappears
