### ISSUE TITLE
Allow public keys which can be shared automatically on the local network

### ISSUE THREAD

**Issue by MarkBennett** [cabal-club/cabal-cli#57]
I'm looking at using cabal for an offline programming camp next year. Without an existing communication channel (ie. email, IM, Slack) I've had to ask people to install [airpaste](https://github.com/mafintosh/airpaste) to broadcast cabal keys so that new users can join a cabal.

Realizing that privacy is a concern and things should be private and remain private by default, I was wondering there was interest in adding a second kind of key that would be broadcast on the network using mDNS or UDP?

Given that users expect existing keys and channels to remain private adding a second type rather than an option to broadcast existing keys seemed to make more sense, but I'd be curious to get others thoughts.

If there's interest in this I'd be happy to put together a PR as I"m looking for an excuse to learn more about dat. Please accept my apology if I'm misunderstanding the terminology or architecture.

Thanks for the awesome work! :)

**Comment by noffle** [comment]
Hi Mark. I think I understand your problem, though I don't understand what
you're suggesting.

If you wanted to share a cabal key over a local network more securely, you could
wrap it in a secret password using gpg:

$ echo 'cabal://...' | gpg -ac -

This will ask you for a passphrase. On the other end you'd do

$ airpaste | gpg -d

to decrypt.

**Comment by MarkBennett** [comment]
Thanks for replying to me @noffle! Sorry if I'm not explaining myself well. I'm still pretty new to dat, etc.

I guess I'm just looking for an easy way to spin up an adhoc wifi network when we're out in woods, and then somehow broadcast the cabal key on the network like how services advertise themselves with mDNS, rather than needing to continually send it out again and again with airpaste.

I'm basically wanting to give up the privacy of the cabal key and *want* an easy way to share it with everyone on my network.

Does cabal support using [`DEP-0005`](https://www.datprotocol.com/deps/0005-dns/)? As a workaround I was thinking I could spin up a DNS server on our network (which I might have to do for other reasons), then setup a DNS record the points cabal://chat to whatever cabal key we setup. If cabal doesn't support using DNS, any interest in a PR to enable it?

Again, I'm still learning about dat so I apologize if I'm misundertanding you're intention with cabal and how it uses dat.

BTW, just watched your demo of cabal the DWeb conference. I really admire what you're trying to do with the project. Thanks for your hard work. 😄

**Comment by noffle** [comment]
Aw thanks for the kind words @MarkBennett :heart:

We don't support dat dns *yet*, [but we really want to](https://github.com/cabal-club/cabal-core/issues/7). I think this would be a really cool way to share cabals more easily. I think it's a pretty small code change, too.

**Comment by noffle** [comment]
We [support this now](https://github.com/cabal-club/cabal-core/issues/7#issuecomment-542799803)!
