### ISSUE TITLE
Newline-containing messages are not wrapped properly

### ISSUE THREAD

**Issue by cinnamon-bun** [cabal-club/cabal-cli#67]
The first line of every message is wrapped ok, but subsequent lines (after newlines) extend too far to the right before getting wrapped, overlapping with the peers panel.

**Comment by kormyen** [comment]
![image](https://user-images.githubusercontent.com/836507/44248057-83eec180-a23c-11e8-839c-72684246aa01.png)
![image](https://user-images.githubusercontent.com/836507/44248062-8f41ed00-a23c-11e8-8573-915f8f21eb20.png)

**Comment by cblgh** [comment]
i think this is fixed? reopen if not
