### ISSUE TITLE
Document hotkeys in client

### ISSUE THREAD

**Issue by MarkBennett** [cabal-club/cabal-cli#68]
My working memory is terrible and I forget hotkeys all the time. Having a `/hotkeys` or `/help hotkeys` command in the client would be great as right now I always refer to the docs on the website:

https://github.com/cabal-club/cabal#hotkeys

**Comment by cblgh** [comment]
+1 we should definitely have this! i

t'd be extra nice if we could use the same file for /hotkeys to generate the hotkey portion of the readme

**Comment by cblgh** [comment]
we do this now with /help i think!
