### ISSUE TITLE
Timeout if there are no peers available

### ISSUE THREAD

**Issue by kodedninja** [cabal-club/cabal-cli#73]
Right now if you try to connect to a key that has no active peers, cabal is trying to connect to it until infinity.

It would be nice to alert the user that there are no peers available and exit the program.

**Comment by noffle** [comment]
We'd probably only want to do this when joining a cabal for the first time, since you may not expect to see any peers if you just created a cabal, or were trying to interact with an existing cabal while offline (queueing messages, reading history).

**Comment by kodedninja** [comment]
@noffle Yes, I meant joining for the first time. Sorry! :smile:
