### ISSUE TITLE
Improve channel notifications

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-cli#82]
* we should be able to see that there is a new message in a channel   
(but as a default i think only showing a sigil `*default` is ideal, rather than a stressful number)
* we should be able to see if we have been mentioned in a channel  
 (but as a default only a sigil `@default`)

**Comment by todrobbins** [comment]
I love/vote for the sigil (`*` or `•`) instead of a number and for `@default` for visualizing a mention. Good ideas, @cblgh!

**Comment by noffle** [comment]
a colour could also work, like weechat or irssi

**Comment by cblgh** [comment]
this is implemented as of https://github.com/cabal-club/cabal-cli/pull/126
